shofi/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('post/<slug:slug>/', views.post, name="post"),
    path('profile/', views.profile, name="profile"),

    # CRUD paths
    path('create-post/', views.createPost, name='create_post'),
    path('update-post/<slug:slug>/', views.updatePost, name='update_post'),
    path('delete-post/<slug:slug>/', views.deletePost, name='delete_post'),

    # Send email path
    path('send-email/', views.sendEmail, name='send_email'),
]

shofi/shofi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

shofi/base/models.py
# from django.db import models
# from django.contrib.auth.models import User

# from django.utils.text import slugify

# from django_ckeditor_5.fields import CKEditor5Field



# # Create your models here.

# class Tags(models.Model):
#     name = models.CharField(max_length=200)
    
#     def __str__(self):
#         return self.name
    

# class Post(models.Model):
#     headline = models.CharField(max_length=200)
#     sub_headline = models.CharField(max_length=200, null=True, blank=True)
#     thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="p.jpg")
#     body = CKEditor5Field('Body', config_name='default', null=True, blank=True)
#     created = models.DateTimeField(auto_now_add=True)
#     activate = models.BooleanField(default=False)
#     featured = models.BooleanField(default=False)
#     tags = models.ManyToManyField(Tags, blank=True)
#     slug = models.SlugField(null=True, blank=True) 
    
#     def __str__(self):
#         return self.headline
    
#     def save(self, *args, **kwargs):
#         if self.slug is None or self.slug == '':
#             slug = slugify(self.headline)
#             has_slug = Post.objects.filter(slug=slug).exists()
#             count = 1
#             while has_slug:
#                 count += 1
#                 slug = slugify(self.headline) + '-' + str(count)
#                 has_slug = Post.objects.filter(slug=slug).exists()
#             self.slug = slug
#         super().save(*args, **kwargs)

# base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field

class Tags(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=50)
    description = models.TextField()
    order = models.IntegerField(default=0)
    class Meta:
        ordering = ['order']
    def __str__(self):
        return self.name

class PricingPlan(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    badge = models.CharField(max_length=50, blank=True)
    popular = models.BooleanField(default=False)
    order = models.IntegerField(default=0)
    class Meta:
        ordering = ['order']
    def __str__(self):
        return self.name

class Feature(models.Model):
    plan = models.ForeignKey(PricingPlan, related_name='features', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    included = models.BooleanField(default=True)
    def __str__(self):
        return self.name

class Client(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='clients/')
    def __str__(self):
        return self.name

class Testimonial(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    content = models.TextField()
    order = models.IntegerField(default=0)
    class Meta:
        ordering = ['order']
    def __str__(self):
        return f"Testimonial by {self.client.name}"

class ContactInfo(models.Model):
    location = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    def __str__(self):
        return "Contact Information"

class SocialLink(models.Model):
    name = models.CharField(max_length=50)
    url = models.URLField()
    icon = models.CharField(max_length=50)
    order = models.IntegerField(default=0)
    class Meta:
        ordering = ['order']
    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.CharField(max_length=100)
    order = models.IntegerField(default=0)
    class Meta:
        ordering = ['order']
    def __str__(self):
        return self.name

class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="p.jpg")
    body = CKEditor5Field('Body', config_name='default', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    activate = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tags, blank=True)
    slug = models.SlugField(null=True, blank=True) 
    
    def __str__(self):
        return self.headline
    
    def save(self, *args, **kwargs):
        if self.slug is None or self.slug == '':
            slug = slugify(self.headline)
            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()
            self.slug = slug
        super().save(*args, **kwargs)

shofi/base/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):
    
    class Meta:
        model = Post
        fields = '__all__'
        
        widgets = {
            'tags':forms.CheckboxSelectMultiple(),
        }

shofi/base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .forms import PostForm
from .filters import PostFilter
from .models import Post, Skill, PricingPlan, Testimonial, ContactInfo, SocialLink, Service


# def home(request):
#     posts = Post.objects.filter(activate=True, featured=True).order_by('-created')[:3]
#     return render(request, 'base/index.html', {'posts': posts})

def home(request):
    posts = Post.objects.filter(activate=True, featured=True).order_by('-created')[:3]
    skills = Skill.objects.all()
    pricing_plans = PricingPlan.objects.all()
    testimonials = Testimonial.objects.all()
    contact_info = ContactInfo.objects.first()
    social_links = SocialLink.objects.all()
    services = Service.objects.all()
    
    context = {
        'posts': posts,
        'skills': skills,
        'pricing_plans': pricing_plans,
        'projects': Post.objects.filter(activate=True).order_by('-created')[:3],  # Use Post as projects
        'testimonials': testimonials,
        'contact_info': contact_info,
        'social_links': social_links,
        'services': services,
        'donation_link': "https://buymeacoffee.com/shofiullah",
    }
    return render(request, 'base/index.html', context)

def posts(request):
    post_list = Post.objects.filter(activate=True).order_by('-created')  # ✅ ordering added
    myFilter = PostFilter(request.GET, queryset=post_list)
    filtered_posts = myFilter.qs

    page = request.GET.get('page')
    paginator = Paginator(filtered_posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'myFilter': myFilter}
    return render(request, 'base/posts.html', context)


def post(request, slug):
    post = get_object_or_404(Post, slug=slug)  # ✅ safer than .get()
    return render(request, 'base/post.html', {'post': post})


def profile(request):
    return render(request, 'base/profile.html')


@login_required(login_url="home")
def createPost(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts')
    return render(request, 'base/post_form.html', {'form': form})


@login_required(login_url="home")
def updatePost(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts')
    return render(request, 'base/post_form.html', {'form': form})


@login_required(login_url="home")
def deletePost(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    return render(request, 'base/delete.html', {'item': post})


def sendEmail(request):
    if request.method == 'POST':
        template = render_to_string('base/email_template.html', {
            'name': request.POST['name'],
            'email': request.POST['email'],
            'message': request.POST['message'],
        })

        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['alsait.shofiullah@gmail.com'],
        )
        email.fail_silently = False
        email.send()

        return render(request, 'base/email_sent.html')

    return redirect('home')  # fallback if accessed via GET

shofi/base/templates/base/delete.html
{% extends 'base/master.html' %}
{% load static %}
{% block content %}

<div class="main-container">
    
    <form action="" method='POST'>
        {% csrf_token %}
        <p>Are you sure you want to delete {{item}}?</p>
        
        <input class='btn btn-danger' type="submit" value='Confirm'>

    </form>
</div>

{% endblock content %}

shofi/base/templates/base/email_sent.html
{% extends 'base/master.html' %}

{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock content %}

shofi/base/templates/base/email_template.html
{{message}}

{{name}}

{{email}}

shofi/base/templates/base/home.html
{% extends 'base/master.html' %}


{% block content %}
<h1>Home</h1>
{% endblock content %}

shofi/base/templates/base/master.html
{% comment %}
<!-- <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Shofi Portfolio</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">   
	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

	<link id="theme-style" rel="stylesheet" type="text/css" href="">
    

</head>
<body>

    {% include 'base/navbar.html' %}

    {% block content %}

    {% endblock content %}

    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>    
	<script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
	
    
</body>
</html> -->

{% endcomment %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shofi Portfolio</title>
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <!-- Swiper CSS -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>
    <!-- Custom Cursor -->
    <div class="cursor"></div>
    <div class="cursor-follower"></div>
    
    <!-- Theme Switcher Toggle -->
    <div class="theme-toggle">
        <i class="fas fa-palette"></i>
    </div>
    
    <!-- Theme Switcher -->
    <div class="theme-switcher">
        <div class="theme-dot" id="light-dot" data-theme="light">
            <span class="theme-label">Light Theme</span>
        </div>
        <div class="theme-dot" id="blue-dot" data-theme="blue">
            <span class="theme-label">Blue Theme</span>
        </div>
        <div class="theme-dot" id="green-dot" data-theme="green">
            <span class="theme-label">Green Theme</span>
        </div>
        <div class="theme-dot" id="purple-dot" data-theme="purple">
            <span class="theme-label">Purple Theme</span>
        </div>
    </div>
    
    <!-- Floating Hire Me Button for Mobile -->
    <a href="#contact" class="floating-hire-btn">Hire Me</a>
    
    <!-- Scroll to Top Button -->
    <div class="scroll-to-top">
        <i class="fas fa-arrow-up"></i>
    </div>
    
    {% include 'base/navbar.html' %}
    {% block content %}
    {% endblock %}
    
    <!-- Scripts -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

shofi/base/templates/base/navbar.html
<nav>
    <div class="nav-logo">
        <span>Shofi</span><span>Dev</span>
    </div>
    <div class="nav-links">
        <a href="#home">Home</a>
        <a href="#skills">Skills</a>
        <a href="#projects">Projects</a>
        <a href="#pricing">Pricing</a>
        <a href="#testimonials">Testimonials</a>
        <a href="#contact">Contact</a>
    </div>
    <button class="btn hire-me-nav">Hire Me</button>
    <button class="hamburger">
        <i class="fas fa-bars"></i>
    </button>
</nav>

shofi/base/templates/base/post.html
{% extends 'base/master.html' %}
{% load static %}

{% block content %}
<style type="text/css">
    img{
        max-width: 100% !important;
        object-fit: cover !important;
    }
</style>

<div class="main-container">
    <img src="{{post.thumbnail.url}}" alt="">
    <h1>{{post.headline}}</h1>
    <h4>{{post.sub_headline}}</h4>
    <p>{{post.body|safe}}</p>

</div>
{% endblock content %}

shofi/base/templates/base/post_form.html
{% extends 'base/master.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
    #div_id_tags > div{
        max-height: 100px;
        overflow: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
    }
</style>

<div class="main-container">
    <h3>Post Form</h3>
    <form action="" method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <input class='btn btn-primary' type="submit" value='Submit Post'>

    </form>
</div>

{% endblock content %}

shofi/base/templates/base/posts.html
{% extends 'base/master.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
    #id_tags{
        overflow-y: scroll;
        max-height: 100px;
        border-radius: 5px;
        padding: 5px;
    }
</style>

<div class='main-container'>
    <h1>Posts</h1>

    {% if request.user.is_staff %}
    <a class="btn btn-warning" href="{% url 'create_post' %}">Create Post</a>
{% endif %}
<form id="searchForm" method="GET">
    {{myFilter.form|crispy}}
    
    <input class="btn btn-primary" type="submit" value="search">
</form>
<br>
<div class="post-wrapper">

    {% for post in posts %}
    <div>
        <div class="post">
            <img class="thumbnail" src="{{post.thumbnail.url}}">
            <div class="post-preview">
                <h6 class="post-title">{{post.headline}}</h6>
                <p class="post-intro">{{post.sub_headline}}</p>
                <a href="{% url 'post' post.slug %}">Read More</a>

                {% if request.user.is_staff %}
                    | <a href="{% url 'update_post' post.slug %}">Edit</a>
                    | <a href="{% url 'delete_post' post.slug %}">Delete</a>
                {% endif %}
                <hr>
                {% for tag in post.tags.all %}
                    <span class="tag">{{tag}}</span>
                {% endfor %}
            </div>
        </div>
    </div>
    {% empty %}
        <h3>No posts found...</h3>
    {% endfor %}
</div>

<div class="row">
    
    {% if posts.has_other_pages %}

        <ul class="pagination">

            {% if posts.has_previous %}
                <li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

                <li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
            {% endif %}


            {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                    <li class="page-item"><a class="active page-link">{{i}}</a></li>
                {% else %}
                    <li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
                {% endif %}
                
            {% endfor %}


            {% if posts.has_next %}
                <li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

                <li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
            {% endif %}
        </ul>

    {% endif %}
</div>
</div>


<script type="text/javascript">
let searchForm = document.getElementById('searchForm')
let pageLinks = document.getElementsByClassName('page-link')

for(var i=0; pageLinks.length > i; i++){

    pageLinks[i].addEventListener('click', function(e){
        e.preventDefault()
        let page = this.dataset.page
        console.log('Page:', page)
        searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
        searchForm.submit()
    })

}
</script>
    
</div>

{% endblock content %}

shofi/base/templates/base/profile.html
{% extends 'base/master.html' %}


{% block content %}
<h1>Profile</h1>
{% endblock content %}